apiVersion: acmpca.aws.crossplane.io/v1alpha1
kind: CertificateAuthority
metadata:
  name: example
spec:
  forProvider:
    region: us-east-1
    permanentDeletionTimeInDays: 7
    type: ROOT
    revocationConfiguration:
      expirationInDays: 7
      enabled: true
      s3BucketName: test-bucket # bucket must already exist
    certificateAuthorityConfiguration:
      keyAlgorithm: RSA_2048
      signingAlgorithm: SHA256WITHRSA
      subject:
        commonName: www.example.com
        country: IN
        locality: example
        organization: example
        organizationalUnit: example
        state: example
    tags:
    - key: Name
      value: example
  providerConfigRef:
    name: example
