apiVersion: rds.aws.crossplane.io/v1alpha1
kind: DBParameterGroup
metadata:
  name: example-dbparametergroup-01
spec:
  forProvider:
    region: eu-central-1
    dbParameterGroupName: createdViaApi
    dbParameterGroupFamily: postgres9.6
    description: test
  providerConfigRef:
    name: aws-provider-config

