ignore:
  field_paths:
    - DescribeDBClustersInput.DBClusterIdentifier
    - CreateDBClusterInput.DBClusterIdentifier
    - ModifyDBClusterInput.DBClusterIdentifier
    - DeleteDBClusterInput.DBClusterIdentifier
    - CreateDBClusterInput.MasterUserPassword
    - ModifyDBClusterInput.MasterUserPassword
    - CreateDBClusterInput.VpcSecurityGroupIds
    - ModifyDBClusterInput.VpcSecurityGroupIds
    - DBCluster.PendingModifiedValues
    - CreateDBParameterGroupInput.DBParameterGroupName
    - DeleteDBParameterGroupInput.DBParameterGroupName
    - ModifyDBParameterGroupInput.DBParameterGroupName
    - DescribeDBParameterGroupInput.DBParameterGroupName
    - DescribeDBParameterGroupsInput.DBParameterGroupName
    - ResetDBParameterGroupInput.DBParameterGroupName
  resource_names:
    - DBClusterEndpoint
    - CustomAvailabilityZone
    - DBClusterParameterGroup
    - DBClusterSnapshot
    - DBInstance
    - DBInstanceReadReplica
    - DBProxy
    - DBSecurityGroup
    - DBSnapshot
    - DBSubnetGroup
    - EventSubscription
    - GlobalCluster
    - OptionGroup
