apiVersion: servicediscovery.aws.crossplane.io/v1alpha1
kind: PrivateDNSNamespace
metadata:
  name: example-privatednsnamespace
spec:
  providerConfigRef:
    name: example
  forProvider:
    region: us-east-1
    description: "test"
    name: crossplane-private-dns-namespace-test
    vpcRef:
      name: sample-vpc
    tags:
      - key: cluster
        value: "my-cluster"
